import { Upgrade } from './data'

export const path = [
	Upgrade.moneyPerQuestion,
	Upgrade.moneyPerQuestion,
	Upgrade.multiplier,
	Upgrade.streakBonus,
	Upgrade.streakBonus,
	Upgrade.multiplier,
	Upgrade.streakBonus,
	Upgrade.streakBonus,
	Upgrade.moneyPerQuestion,
	Upgrade.multiplier,
	Upgrade.streakBonus,
	Upgrade.multiplier,
	Upgrade.multiplier,
	Upgrade.moneyPerQuestion,
	Upgrade.streakBonus,
	Upgrade.moneyPerQuestion,
	Upgrade.multiplier,
	Upgrade.moneyPerQuestion,
	Upgrade.moneyPerQuestion,
	Upgrade.moneyPerQuestion,
	Upgrade.multiplier,
	Upgrade.streakBonus,
	Upgrade.moneyPerQuestion,
	Upgrade.moneyPerQuestion,
	Upgrade.moneyPerQuestion,
]
